### ISSUE TITLE
some question about the metrics

### ISSUE THREAD

**Issue by zyq-20000901** [guaguabujianle/MGraphDTA#5]
hello!
recently, I read your paper ' MGrapgDTA'.
I have some questions about this.
I wanna know what the number in the'()' means.
Is it "std"?
if yes, how can I calculate it?

![Snipaste_2023-03-18_15-34-37](https://user-images.githubusercontent.com/58555718/226092051-9d9fd141-c89d-472a-a91e-82f93768eb69.png)

**Comment by guaguabujianle** [comment]
Yes, it is std. As described in the paper, all experiments are repeated three times, so finally you will get three results for each metric. Then you can calculate the mean and std of the three results.

**Comment by zyq-20000901** [comment]
Thank you for your reply and wish you all the best！
